@echo off
CHCP 65001>NUL

ECHO.                                                                                                                                                2>nul  > "%Temp%\Autorun.txt"
ECHO        Autorun Folder User:                                                                                                                     2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
dir /b /s "C:\Users\%UserName%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\"                                                       2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
ECHO        Autorun Folder PC:                                                                                                                       2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
dir /b /s "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\"                                                                            2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
ECHO        Autorun Registry User:                                                                                                                   2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"                                                                                       2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\Software\Microsoft\Windows\CurrentVersion\RunOnce"                                                                                   2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run"                                                              2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run32"                                                            2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\StartupFolder"                                                    2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\Software\Microsoft\Windows\CurrentVersion\RunServices"                                                                               2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce"                                                                           2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run"                                                                     2>nul >> "%Temp%\Autorun.txt"
:: REG QUERY "HKCU\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"                                                                            2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
ECHO        Autorun Registry PC:                                                                                                                     2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"                                                                                       2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce"                                                                                   2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run"                                                                           2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\RunOnce"                                                                       2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run"                                                              2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run32"                                                            2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\StartupFolder"                                                    2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\Software\Microsoft\Windows\CurrentVersion\RunServices"                                                                               2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\Software\Microsoft\Windows\CurrentVersion\RunServicesOnce"                                                                           2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run"                                                                     2>nul >> "%Temp%\Autorun.txt"
:: REG QUERY "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon"                                                                            2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
ECHO.                                                                                                                                                2>nul >> "%Temp%\Autorun.txt"
ECHO        Autorun Registry UWP:                                                                                                                    2>nul >> "%Temp%\Autorun.txt"
REG QUERY "HKCU\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData" /S /F "startup" |findstr /I /V ":" 2>nul >> "%Temp%\Autorun.txt"

"%Temp%\Autorun.txt"
del /q "%Temp%\Autorun.txt"