@echo off
CHCP 65001>NUL

ECHO.                                                                     2>nul  > "%temp%\ContextMenu.txt"
ECHO        Desktop:                                                      2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Directory\Background\shell"                               2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Directory\Background\shellex\ContextMenuHandlers"         2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        Desktop Background:                                           2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\DesktopBackground\Shell"                                  2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\DesktopBackground\shellex\ContextMenuHandlers"            2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        Directory:                                                    2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Directory\shell"                                          2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Directory\shellex\ContextMenuHandlers"                    2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        Send To:                                                      2>nul >> "%temp%\ContextMenu.txt"
dir /b /s "C:\Users\%UserName%\AppData\Roaming\Microsoft\Windows\SendTo\" 2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        This PC:                                                      2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\shell"       2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        Recycle:                                                      2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\shell"       2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        Folder                                                        2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Folder\shell"                                             2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Folder\shellex\ContextMenuHandlers"                       2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        Drive:                                                        2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Drive\shell"                                              2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\Drive\shellex\ContextMenuHandlers"                        2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        File:                                                         2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\*\shell"                                                  2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\*\shellex\ContextMenuHandlers"                            2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        EXE File:                                                     2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\exefile\shell"                                            2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\exefile\shellex\ContextMenuHandlers"                      2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        LNK Link:                                                     2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\lnkfile\shellex\ContextMenuHandlers"                      2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO.                                                                     2>nul >> "%temp%\ContextMenu.txt"
ECHO        Other:                                                        2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\AllFilesystemObjects\shell"                               2>nul >> "%temp%\ContextMenu.txt"
REG QUERY "HKCR\AllFilesystemObjects\shellex\ContextMenuHandlers"         2>nul >> "%temp%\ContextMenu.txt"

"%temp%\ContextMenu.txt"
del /q "%temp%\ContextMenu.txt"